### ISSUE TITLE
respecter les dimension

### ISSUE THREAD

**Issue by SALAH-EDDIB** [HILMIONELL97/OUR-WEB-SITE#10]
## Mise en page

Les dessins ont été créés dans les largeurs suivantes :

- Mobile : 375px
- Bureau : 1440px
- tablete : 800px

**Comment by HILMIONELL97** [comment]
OK ça Marche MS EDDIB.
NB: Moi Je Suis  d accord  avec les tailles de mobile et tablete ,mais avec le desktop on peux travaillé sur 1440 ou plus .(moi je travaille sur 1518 px)ANY WAY .

**Comment by SALAH-EDDIB** [comment]
ok c'est bien

**Comment by ahmedmoutaalim** [comment]
merci de me rappeler .
