### ISSUE TITLE
responsive par utilisation flexbox

### ISSUE THREAD

**Issue by ahmedmoutaalim** [HILMIONELL97/OUR-WEB-SITE#11]
j'ai besoin un peu de documentation pour realiser responsive tab et mob par flexbox 
et comme vous le savez documentation=temps  :)

**Comment by HILMIONELL97** [comment]
nous avons Aucun problem, take your time Ahmed.

**Comment by HILMIONELL97** [comment]
HELLO, AGAIN THIS VIDEO IS GONNA BE A SOLUTION FOR YOUR PROBLEME OK, TRUST ME IT'S SO HELPFUL::https://www.youtube.com/watch?v=srvUrASNj0s&t=939s.
NB: l video twill xwiya ms rah harab f niveau ok

**Comment by ahmedmoutaalim** [comment]
merci de votre attention 👍
