### ISSUE TITLE
Problem d 'hébèrgement  

### ISSUE THREAD

**Issue by HILMIONELL97** [HILMIONELL97/OUR-WEB-SITE#12]
j ai trouvé un Problem au niveau d' hébérgement de mon index sachant que le lien qui lui donner et :
https://hilmionell97.github.io/OUR-WEB-SITE.  I'm waiting for your replies .

**Comment by SALAH-EDDIB** [comment]
il faut que le fichier html étre on branch master

**Comment by HILMIONELL97** [comment]
AH , Bon J' ai totalement oublié.
MRC SALAH
