### ISSUE TITLE
FONT-FAMILY "MONTSERRAT"

### ISSUE THREAD

**Issue by HILMIONELL97** [HILMIONELL97/OUR-WEB-SITE#13]
guys, j ' ai trouvé  qu' aucune  personne travaille  avec la font que  je donne à vous en UI style .
NB: vous êtes oubliger  de respecter UI STYLE GUIDE  et merci.

**Comment by ahmedmoutaalim** [comment]
tu veux dire font de texte ou quoi !?

**Comment by HILMIONELL97** [comment]
oui ms Ahmed la font du texte . Tu dois le corriger  ok.

**Comment by HILMIONELL97** [comment]
### THANKS FOR YOUR ATTENTION
